import React from "react";
const GlobalContext = React.createContext({
  monthIndex: 0,
  setMonthIndex: (index) => {},
  smallCalendarMonth: 0,
  setSmallCalendarMonth: (index) => {},
  daySelected: null,
  setDaySelected: (day) => {},
  showEventModal: false,
  setShowEventModal: () => {},
  dispatchCalEvent: ({ type, payload }) => {},
  savedEvents: [],
  selectedEvent: null,
  setSelectedEvent: () => {},
  labels: [],
  setLabels: () => {},
  updateLabel: () => {},
  filteredEvents: [],
  calendarEvents: [],
  setCalendarEvents: () => {},
  patientData: [],
  setPatientData: () => {},
  selectedPatient: null, 
  setSelectedPatient: () => {},
  submittedEvent: null, 
  setSubmittedEvent: () => {},
  showValidationPopUp: false,
  setShowValidationPopUp: () => {},
  currEventId: 12,
  setCurrEventId: () => {},
}); 
export default GlobalContext;
