CREATE TABLE CALENDAR_EVENTS
    (
	 EVENT_ID NUMBER(8),
     START_DATE_TIME DATE,
	 END_DATE_TIME DATE,
	 IS_ALL_DAY_EVENT CHAR(1) NOT NULL,
	 LOCATION VARCHAR2(100),
	 PATIENT_ID NUMBER(8) NOT NULL,
	 EVENT_LABEL VARCHAR2(8) NOT NULL,
	 EVENT_TITLE VARCHAR2(50) NOT NULL,
	 EVENT_DESCRIPTION VARCHAR2(100),
	 
	 PRIMARY KEY (EVENT_ID),
	 FOREIGN KEY (PATIENT_ID) REFERENCES USERS(ID),
	 
	 CONSTRAINT check_is_all_day_event
     CHECK (is_all_day_event IN ('T', 'F')),
	 
	 CONSTRAINT check_event_label
	 CHECK (event_label IN ('indigo', 'gray', 'green', 'blue', 'red', 'purple'))
     );

CREATE TABLE RECURRENCES
    (
	 RECURRENCE_ID NUMBER(8),
	 EVENT_ID NUMBER(8),
	 RECURRENCE VARCHAR2(10) NOT NULL,
	 NUM_OCCURENCES NUMBER(8,0),
	 DAY_OF_WEEK VARCHAR2(10),
	 NUM_OF_MONTH NUMBER (2,0),
	 
	 PRIMARY KEY (RECURRENCE_ID),
	 FOREIGN KEY (EVENT_ID) REFERENCES CALENDAR_EVENTS (EVENT_ID),
	 
	 CONSTRAINT check_reccurence
	 CHECK (recurrence IN ('Daily', 'Weekly', 'Monthly', 'Yearly')),
	 
	 CONSTRAINT check_day_of_week
	 CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
	 
	 CONSTRAINT check_num_of_month
	 CHECK (num_of_month >= 1 AND num_of_month <= 31)
	);

CREATE TABLE USERS
	(
		ID NUMBER(8),
		FIRST_NAME VARCHAR2(30),
		LAST_NAME VARCHAR(30),
		SEX CHAR(1),

		PRIMARY KEY (ID),

		CONSTRAINT check_sex
		CHECK(sex IN ('F', 'M'))
	);

INSERT INTO CALENDAR_EVENTS
(EVENT_ID, START_DATE_TIME, END_DATE_TIME, IS_ALL_DAY_EVENT, LOCATION,
PATIENT_ID, EVENT_LABEL, EVENT_TITLE)
VALUES
(00000001, TO_DATE('17-JAN-2022 14:00:00', 'DD-MON-YYYY HH24:MI:SS'), TO_DATE('17-JAN-2022 15:30:00', 'DD-MON-YYYY HH24:MI:SS'),
'F', 'MS TEAMS', 1, 'indigo', 'Meeting w/ supervisor');

INSERT INTO CALENDAR_EVENTS
(EVENT_ID, START_DATE_TIME, END_DATE_TIME, IS_ALL_DAY_EVENT, LOCATION,
PATIENT_ID, EVENT_LABEL, EVENT_TITLE, EVENT_DESCRIPTION)
VALUES
(00000002, TO_DATE('15-MAY-2022 13:00:00', 'DD-MON-YYYY HH24:MI:SS'), TO_DATE('15-MAY-2022 14:00:00', 'DD-MON-YYYY HH24:MI:SS'),
'F', 'White Rock Dental', 2, 'green', 'Dentist Appointment', 'Getting braces off');

INSERT INTO CALENDAR_EVENTS
(EVENT_ID, START_DATE_TIME, END_DATE_TIME, IS_ALL_DAY_EVENT, LOCATION,
PATIENT_ID, EVENT_LABEL, EVENT_TITLE)
VALUES
(00000003, TO_DATE('01-JUN-2022 11:00:00', 'DD-MON-YYYY HH24:MI:SS'), TO_DATE('01-JUN-2022 14:00:00', 'DD-MON-YYYY HH24:MI:SS'),
'F', 'UBC', 3, 'blue', 'CPSC 213 Exam');

INSERT INTO CALENDAR_EVENTS
(EVENT_ID, START_DATE_TIME, END_DATE_TIME, IS_ALL_DAY_EVENT, LOCATION, PATIENT_ID, EVENT_LABEL, EVENT_TITLE)
VALUES
(00000004, TO_DATE('22-JUN-2022', 'DD-MM-YYYY'), TO_DATE('22-JUN-2022', 'DD-MM-YYYY'),'T', 'St. Pauls Hospital', 4 'green', 'Liver Transplant')

INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (1,'SINGH','TAJINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (2,'ALI','DWAIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (3,'ALI','JAMES G','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (4,'ALI','PARWINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (5,'JOHNSTON','AZITA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (6,'ALI','BONIFACIO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (7,'SINGH','BERTA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (8,'MOORE','MOHAMMED','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (9,'SINGH','SHAM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (10,'ALI','ANDRIES','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (11,'TURNER','SHAHROKH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (12,'ALI','NAVID','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (13,'SINGH','LIAM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (14,'ALI','MUNI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (15,'ALI','NICOLAS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (16,'SINGH','CELIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (17,'ALI','FRED','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (18,'ALI','BIENVENIDO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (19,'ALI','NANETTE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (20,'ALI','MANJIT','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (21,'ANDERSON','PRITAM','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (22,'ALI','RAMINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (23,'CAMPBELL','ONA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (24,'TURNER','LAI FONG','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (25,'ALI','GYAN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (26,'CAMPBELL','CLARA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (27,'SINGH','MANJEET','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (28,'ALI','JOAN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (29,'ALI','LEON','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (30,'WOOD','SUKHVINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (31,'ALI','CARISSA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (32,'TURNER','BASILIO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (33,'ALI','VERNA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (34,'GREWAL','KERRIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (35,'TURNER','ZAIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (36,'TURNER','BRUCE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (37,'STEWART','HARPAL','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (39,'ALI','EVERT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (40,'ALI','ROSALIND','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (41,'ALI','MARINUS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (42,'SINGH','CLAUDINE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (43,'CAMPBELL','NICOLETTE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (44,'TURNER','BJARNE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (45,'SINGH','MARLON','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (46,'ALI','LUZVIMINDA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (47,'ALI','LYLE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (48,'SINGH','DAVID','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (49,'ALI','SERGE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (50,'ALI','ALINE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (51,'ALI','ADEL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (53,'ALI','HAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (54,'ALI','IVO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (55,'ALI','PARVIN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (56,'ALI','JUNG','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (58,'SINGH','YICK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (59,'ALI','LAILA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (60,'ALI','SERGEI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (61,'ALI','ONKAR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (62,'ALI','FARIDEH','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (63,'TURNER','AUDREY','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (66,'ALI','KIMBERLEY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (67,'TURNER','WENDE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (70,'ALI','SADRU','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (71,'TURNER','JEFFRY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (72,'ALI','DELILAH','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (74,'ALI','TRICIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (75,'ALI','FERDINANDO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (78,'ALI','POOJA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (80,'TURNER','TU','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (81,'ALI','MARY-ANN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (82,'TURNER','MARC','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (83,'SINGH','AMANDA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (86,'ALI','FRAN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (87,'ALI','SATINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (88,'TURNER','TED','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (89,'CAMPBELL','CARYL','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (91,'ALI','NING','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (92,'ALI','RAE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (93,'SMITH','VOLKER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (94,'TURNER','MUMTAZ','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (95,'TURNER','WENDE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (96,'JOHNSTON','ASAD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (97,'ALI','JIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (98,'ALI','KRISTIN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (99,'TURNER','ELSIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (100,'SINGH','ROSEANN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (38,'ANDERSON','NIZAR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (52,'ALI','SUSANNA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (57,'MOORE','MANJINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (64,'SINGH','GEERTRUIDA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (76,'SINGH','REINHOLD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (84,'SINGH','MIMI','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (65,'MOORE','KATALIN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (85,'MOORE','KENNETH JOHN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (68,'SINGH','JULIETTE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (69,'SINGH','SONIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (77,'SINGH','ARDEN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (73,'TURNER','FERDINANDO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (90,'TURNER','IOAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (79,'TURNER','DONNIE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (102,'ALI','RUDY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (103,'ALI','RAJENDRA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (104,'CAMPBELL','HOK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (105,'TURNER','SIGMUND','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (106,'TURNER','CST-LGHONE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (108,'TURNER','JARRETT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (109,'ALI','REMEDIOS','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (112,'JOHNSTON','FEIZAL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (113,'TURNER','MAHNAZ','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (114,'SINGH','JESSE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (115,'HENDERSON','NASIR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (116,'ALI','MARY-LOU','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (117,'ALI','LILLY','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (118,'ANDERSON','LORNE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (119,'HENDERSON','GIANFRANCO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (120,'CAMPBELL','MANINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (121,'CAMPBELL','YOSHIO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (122,'JOHNSTON','MOSES','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (123,'HENDERSON','EDMUND','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (125,'ANDERSON','KLARA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (126,'ANDERSON','RENZO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (127,'ANDERSON','GLENDA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (129,'SINGH','SHOU','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (130,'ANDERSON','AJMER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (131,'TURNER','MOISES','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (132,'REID','AHMET','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (133,'SINGH','LEOPOLDO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (134,'HENDERSON','SUKHWANT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (135,'ANDERSON','KAI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (136,'CAMPBELL','GISELA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (138,'SINGH','PARISA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (139,'THOMPSON','JULIAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (140,'HENDERSON','LOUIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (141,'HENDERSON','KAREL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (142,'SINGH','JANEL','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (143,'ANDERSON','GURDAWAR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (144,'ANDERSON','VLADISLAV','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (145,'HENDERSON','FARIBA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (146,'ANDERSON','ADELIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (148,'ANDERSON','LOTTIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (150,'ANDERSON','RAMENDRA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (151,'CAMPBELL','KIRK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (152,'ANDERSON','MACKENZIE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (153,'TURNER','KULWINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (154,'GRAHAM','MARY JANE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (155,'ANDERSON','ANTOINETTE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (156,'HENDERSON','KIRSTEN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (157,'ANDERSON','DAYA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (158,'SINGH','RAJINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (159,'MORRISON','SAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (160,'HENDERSON','DALJIT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (161,'ANDERSON','WAYNE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (162,'MOORE','VIJAY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (163,'ANDERSON','BRENNAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (164,'SINGH','FORREST','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (165,'ANDERSON','GURINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (166,'HILL','JOGA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (169,'HENDERSON','BORIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (171,'ANDERSON','SALIM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (174,'SINGH','ALENA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (176,'SINGH','KYLIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (177,'SINGH','LAURI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (178,'MORRISON','XIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (179,'ANDERSON','FLORIAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (180,'HENDERSON','ASHRAF','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (181,'ANDERSON','GURMIT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (182,'ANDERSON','GREIG','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (183,'ANDERSON','ROSALINDA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (184,'HENDERSON','VAHID','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (185,'ANDERSON','MOHSEN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (186,'TURNER','LORETA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (187,'SINGH','DRAGO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (188,'ALI','TRISHA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (189,'TURNER','SHAHIN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (190,'ALI','LALITA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (191,'ALI','CATHERINE ANN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (192,'JOHNSTON','SANDRA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (193,'HENDERSON','INDERJEET','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (195,'WILSON','JONI','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (196,'ANDERSON','JASBIR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (197,'SINGH','REINHART','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (198,'DAVIS','ELIAS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (199,'SINGH','HENDRICK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (200,'ANDERSON','CHRISTINA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (201,'CAMPBELL','JOANN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (202,'ANDERSON','REBECA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (203,'HENDERSON','JAY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (204,'CAMPBELL','WILHELM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (205,'ANDERSON','SHANE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (206,'ANDERSON','JATINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (207,'MACDONALD','JOHANNES','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (101,'SINGH','CHASE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (107,'GRAHAM','DAMIAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (110,'LAU','CHRISTIANA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (111,'STEWART','BHAGWANT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (124,'LIU','BRIAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (128,'SINGH','SURENDRA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (149,'SINGH','KEHAR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (137,'HENDERSON','JOHN MICHAEL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (167,'MOORE','AUGUSTUS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (168,'MACDONALD','RICHARD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (170,'ROBERTS','WILLARD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (172,'HUANG','SUNG','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (175,'HO','DAREN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (194,'ANDERSON','WILLIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (208,'ANDERSON','JESSICA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (209,'ALI','GABRIEL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (210,'HENDERSON','CHUNG','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (211,'CAMPBELL','MANDEEP','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (212,'CAMPBELL','SAVITA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (213,'TURNER','SHEILA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (214,'CAMPBELL','TEJ','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (215,'ALI','LACHMAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (216,'ALI','JACEK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (217,'TURNER','RAINER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (218,'ALI','CESAR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (219,'CAMPBELL','PHILIP','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (220,'ALI','GEORGIOS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (221,'SINGH','TOMISLAV','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (222,'ALI','RICHMOND','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (223,'ALI','ZAHIR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (224,'ALI','ED','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (225,'SINGH','NEVILLE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (226,'SINGH','BRODY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (227,'TURNER','HARINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (228,'MOORE','LAUREL','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (229,'TURNER','ROXANN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (230,'TURNER','DARCY','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (231,'ALI','HUA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (232,'JOHNSTON','AYESHA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (233,'CAMPBELL','NARANJAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (236,'ALI','KOUROSH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (237,'CAMPBELL','JING','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (238,'ALI','JAMES A','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (240,'TURNER','MANUEL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (241,'TURNER','BRANISLAV','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (242,'ALI','SALAH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (243,'TURNER','TAKESHI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (244,'ALI','KEN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (245,'ALI','NOORALI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (246,'TURNER','KELLY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (247,'SINGH','VALERIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (248,'ALI','MIKHAIL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (249,'TURNER','THU','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (250,'ALI','VERNA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (251,'ALI','JOEY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (252,'TURNER','PAIGE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (253,'ALI','HARDEEP','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (254,'STEWART','FERNE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (255,'SINGH','JAGDEV','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (257,'ALI','LAI FONG','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (258,'ALI','MARY LEE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (259,'ALI','MIRA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (260,'ALI','MARGARIDA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (261,'MILLER','CHIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (262,'CAMPBELL','SUMITA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (264,'SINGH','LAI','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (265,'ALI','FELICIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (266,'ALI','HOSSEIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (267,'ROBINSON','FAEZEH','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (268,'ALI','KUN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (269,'TURNER','PATRICIA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (270,'ALI','ERMA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (271,'CAMPBELL','SILVANO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (272,'TURNER','STEVE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (273,'CAMPBELL','PREM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (274,'ALI','CHAU','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (275,'ALI','GEORGE WILLIAM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (277,'JOHNSTON','JALAL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (278,'CAMPBELL','KRISTEN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (279,'ALI','MANMOHAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (280,'ALI','TERRY','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (281,'SINGH','LANI','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (283,'ALI','SOPHIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (284,'SINGH','MARIKA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (286,'MOORE','NORBERTO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (287,'ALI','KIM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (288,'SINGH','RHEA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (289,'ALI','SHARLEEN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (290,'ALI','LOUELLA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (292,'THOMPSON','WILLA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (293,'ALI','EUGENE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (294,'TURNER','ELISABETH','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (295,'SINGH','DALIP','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (296,'MILLER','PRADEEP','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (297,'ALI','CODY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (298,'ALI','XIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (299,'SMITH','LAVINA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (300,'SINGH','GEORGETTE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (301,'SINGH','AMELITA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (303,'ALI','BERTHA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (234,'STEWART','MILDRED','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (235,'SINGH','PARVINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (239,'SHARMA','TONYA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (256,'CHEN','DEVIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (276,'REID','SIK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (282,'CHEUNG','BYRON','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (285,'TURNER','HUU','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (291,'LIU','VALENTINE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (302,'HO','RAMESH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (307,'ALI','RACHHPAL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (308,'TURNER','JONAH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (309,'ALI','MANPREET','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (310,'MOORE','DENNIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (311,'TURNER','KULWINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (312,'SINGH','GEOFFREY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (313,'ALI','PETER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (314,'ALI','CHANG','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (315,'TURNER','DARRELL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (316,'SINGH','BOZENA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (317,'ALI','ELLIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (318,'TURNER','BLANCA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (319,'CHOW','LIDA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (320,'SINGH','AMINA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (321,'ALI','DEXTER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (322,'TURNER','CRISTIAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (323,'ALI','JERZY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (324,'ALI','ALBINA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (325,'ALI','GHEORGHE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (326,'ALI','RAILI','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (328,'ALI','MARCUS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (329,'ALI','SHAYNE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (331,'ALI','GAGAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (332,'ALI','QING','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (333,'ALI','MAHNAZ','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (334,'SINGH','KALEB','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (335,'ALI','GAEL','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (336,'CAMPBELL','SULTANALI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (337,'TURNER','ROMEO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (338,'ALI','CHRISTOPHER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (339,'TURNER','ERROL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (340,'SINGH','LAJOS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (341,'SINGH','PHYLLIS','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (342,'TURNER','HAROLD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (343,'ALI','REYNOLD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (344,'ALI','JAGIR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (345,'TURNER','SATINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (346,'CAMPBELL','ELINOR','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (348,'SINGH','BRAYDON','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (351,'CAMPBELL','WAH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (352,'SINGH','RAPHAEL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (353,'TURNER','ASHRAF','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (354,'MORRISON','FAISAL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (304,'SINGH','MARISSA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (305,'ANDERSON','HOLLY','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (306,'WOOD','KULBIR','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (327,'CHEUNG','JOSEFINA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (330,'NELSON','PREM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (347,'ALI','LISA MARIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (349,'ALI','ANIKA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (350,'ALI','PETR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (357,'ALI','DARREN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (358,'TURNER','KIRBY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (359,'SINGH','DAGMAR','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (360,'ALI','LEONARDO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (361,'SINGH','KRISTIAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (362,'TURNER','CHRISTIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (363,'ALI','RAMINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (364,'ALI','NOEL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (365,'SINGH','HARRISON','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (366,'ALI','MOLLY','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (367,'TURNER','KRISTOPHER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (369,'SINGH','KE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (372,'SINGH','DOMENIC','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (373,'TURNER','CLIVE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (374,'SINGH','BAKHSHISH','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (377,'HENDERSON','VINCENT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (378,'SINGH','MANI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (381,'SINGH','THERESSA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (382,'ALI','GURDEV KAUR','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (355,'ROBERTS','NADIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (356,'EVANS','WING','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (368,'BROWN','RINA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (370,'ALI','AKRAM','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (371,'ALI','HARNEK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (375,'ALI','LASZLO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (376,'ALI','IVAR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (379,'ALI','JACKSON','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (380,'ALI','VACLAV','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (383,'ALI','CONSTANTINO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (384,'GREWAL','CYRIL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (385,'SINGH','MAKOTO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (386,'TURNER','MANPREET','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (387,'ALI','SARJIT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (388,'HENDERSON','ERICK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (389,'TURNER','NATHALIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (390,'ALI','CHARANJIT','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (391,'HENDERSON','MARLENE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (392,'SINGH','PERLA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (393,'TURNER','MADONNA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (394,'ALI','SANDRA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (395,'LI','SHARRON','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (396,'HILL','LARISA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (397,'SINGH','ALAIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (399,'ALI','NORMA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (400,'NELSON','PETER JAMES','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (402,'ALI','KARIM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (403,'WU','DENICE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (404,'HENDERSON','WARD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (405,'ALI','BORIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (406,'HENDERSON','AMIT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (408,'SINGH','EARNEST','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (409,'ALI','KELSEY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (410,'ALI','CODY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (411,'ALI','BETTIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (412,'WONG','QUANG','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (413,'SINGH','ARMAAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (414,'TURNER','LYNN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (415,'ALI','HESTER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (416,'ALI','LAKHBIR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (417,'ALI','IRVING','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (418,'ALI','MIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (419,'ALI','TEJINDER','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (420,'SINGH','ALOIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (421,'ALI','ADRIANO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (423,'NELSON','MARIS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (424,'SINGH','SHEILA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (425,'ALI','HUGO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (426,'ALI','UDO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (427,'ALI','AMAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (429,'HENDERSON','SATWANT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (430,'SINGH','TEJA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (431,'HENDERSON','WAI LAN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (432,'ALI','LUKA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (433,'HAMILTON','LACHHMAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (434,'SINGH','ROYCE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (435,'ALI','AHMAD','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (436,'SINGH','ARLEEN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (439,'GREWAL','SATINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (441,'NELSON','RAJBIR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (444,'TURNER','RANI','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (445,'TURNER','TARAS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (446,'SINGH','KADEN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (449,'SINGH','PARGAT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (450,'SINGH','LEIGH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (451,'ALI','SHENG','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (452,'ALI','ONKAR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (453,'HENDERSON','SYLVESTER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (454,'STEWART','MICHELINE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (455,'ALI','ETHAN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (456,'ALI','AVELINO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (457,'WONG','ROZMIN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (458,'SINGH','GUILLERMO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (459,'SINGH','SAVERIO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (460,'CAMPBELL','XIU','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (398,'MARTIN','ORVILLE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (401,'DAVIS','RACHELLE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (428,'HALL','LAURIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (437,'CAMPBELL','PARAMJEET','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (438,'ALI','GLYN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (440,'ALI','JESSE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (443,'ALI','MORLEY','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (448,'ALI','YVES','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (442,'HENDERSON','GURDEV KAUR','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (447,'LEWIS','ROYCE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (464,'BAINS','MIRCEA','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (465,'TURNER','LAKHWINDER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (469,'CAMPBELL','JOANN','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (471,'TURNER','SHELLY','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (472,'TURNER','AKBER','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (473,'TURNER','ASHOK','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (474,'TURNER','HIROKO','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (475,'ALI','ANGUS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (476,'ALI','CELESTINA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (477,'ALI','BENNETT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (478,'TURNER','BASANT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (479,'ALI','LEENA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (480,'ALI','VIRGINIA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (481,'ALI','ROSE MARIE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (482,'TURNER','HOSSEIN','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (483,'SINGH','SULTANALI','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (484,'WOOD','JOZEF','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (486,'TURNER','KAM','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (489,'SINGH','SUBHASH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (490,'CAMPBELL','KAM WING','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (491,'MOORE','NIEL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (492,'SINGH','VISHAL','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (495,'CAMPBELL','BOGUSLAW','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (496,'TURNER','LUCAS','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (497,'TURNER','LEONA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (498,'ALI','DOMINADOR','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (462,'MOORE','BEATRIZ','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (487,'MOORE','ROBERT WILLIAM','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (463,'ALI','CHIH','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (466,'ALI','BRUCE','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (468,'ALI','MARLENE','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (494,'ALI','OREST','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (467,'ROSS','LAVERNA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (470,'SINGH','AIKO','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (485,'ALI','LAURENT','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (488,'ALI','PREMILA','F');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (493,'ALI','STANKO','M');
INSERT INTO USERS (ID,LAST_NAME,FIRST_NAME,SEX) VALUES (499,'ALI','MUKHTIAR','M');
